version: '2'
services:
  factorial:
    build: ./balena_factorial
    privileged: false
    restart: never
    #network_mode: host
  hello:
    build: ./balena_hello_world
    restart: always
    privileged: false
  server:
    restart: always
    build: ./balena_simple_server
    ports:
      - "80"

